Added (Dutch) phonenumber recognition
EmicoEcommerce/Magento2RobinHq pull request #40
Opened 2022-06-07 06:41 UTC by cjfloermans

Hi Bram,
As agreed I've added a validation for phone numbers.
I've added 3 regular expressions to recognise Dutch format (+31XXXXXXXXX, 0031XXXXXXXXX, 0XXXXXXXXX) and finally if the number is numeric at all. In all these cases the last 9 digits are returned. Otherwise it is False and no search on phone number is done (this also fixes 'double searches' in that field imho).

2022-06-07 07:52 UTC, bramstroker commented
Thanks @cjfloermans.

Seems fine by me.
This removes the possibility to search with telephone numbers starting with a specific string, but this makes no sense to me anyway as the user does not know in which format the value exists in the database.

An improvement would be to search for 3 literal values instead of a LIKE `%...` as for the last case no index can be used, and this gets exponentially problematic when the amount of records in the database increases.

When the user searches for `0612345678` (or any other dutch format), we can take the last 9 characters `612345678`,
and than construct the where to be `billing_telephone IN ('0612345678', '+31612345678', '0031612345678')`.
Now an index can be used and the query should be lightning fast.

2022-06-09 07:39 UTC, cjfloermans commented
Hi Bram,
I've implemented your proposal;

First a test is performed if the search term seems to be a Dutch phone number by 3 regular expressions. When this evaluates to true, a literal search is done by those three possibilities. If it evaluates to false, a fallback is in place to search the like '%[LAST 9 DIGITS]' when it's a numeric value, to support searches for other countries as well.
Please see this example for the international format (and the 2 other options 0031[9 DIGITS] and 0[9 DIGITS] gave the same response;
![robin_result_phone](https://user-images.githubusercontent.com/1148227/172791944-7e3ee3bf-dfcc-4c59-bd19-1b9943ea868e.png)

2022-06-09 08:16 UTC, bramstroker requested changes

2022-06-09 08:16 UTC, bramstroker commented on src/DataProvider/SearchDataProvider.php
> +    protected function createPhoneNumberSearchFilter($searchTerm): ?Filter
```suggestion
    protected function createPhoneNumberSearchFilter(string $searchTerm): ?Filter
```

2022-06-09 08:16 UTC, bramstroker commented on src/DataProvider/SearchDataProvider.php
> +    protected function parsePhoneNumber($searchTerm)
```suggestion
    protected function parsePhoneNumber(string $searchTerm)
```

2022-06-09 08:16 UTC, bramstroker commented on src/DataProvider/SearchDataProvider.php
> +    protected function seemsDutchNumber($searchTerm): bool
```suggestion
    protected function seemsDutchNumber(string $searchTerm): bool
```

2022-06-09 08:16 UTC, bramstroker commented on src/DataProvider/SearchDataProvider.php
> +    protected function createDutchPhoneNumbers($phoneNumber): array
```suggestion
    protected function createDutchPhoneNumbers(string $phoneNumber): array
```

2022-06-09 08:32 UTC, merged